### ISSUE TITLE
Using caching and TRACKING invalidation process

### ISSUE THREAD

**Issue by MosheLOptimove** [redis/node-redis#2504] opened 2023-05-11 09:06 UTC
Hello,

We are working on a real-time application (i.e. low latency requirement) and have a REDIS data source. Currently we have an internal caching package that overrides node-redis' functionalities.

I'm trying to see if we can deprecated that package and use the formal package instead, but I couldn't find any example for using caching (or the new TRACKING functionality). Does a caching mechanism exists in this package? and if so, can you point me to some code-based resources?

Thanks,
Moshe

**Comment by leibale** [comment] 2023-05-11 09:32
I'm assuming you are talking about "[client-side caching](https://redis.io/docs/manual/client-side-caching/)"? The plan is:
5.0: RESP3 + more features
5.1: Sentinel support
5.2: Client-side caching

Duplicate of #1623

**Closed by leibale** 2023-05-11 09:32 UTC

**Comment by MosheLOptimove** [comment] 2023-05-11 09:34
Thanks, I'll subscribe to that issue
