### ISSUE TITLE
Turning on pingInterval on a pubsub channel results in an error

### ISSUE THREAD

**Issue by mdouglass** [redis/node-redis#2372] opened 2023-01-09 22:13 UTC
If you turn on pingInterval on a client using pubsub features, the client errors out and returns `Error: Cannot send commands in PubSub mode`. This is incorrect because PING is one of the allowed commands on a PUBSUB channel.

**Environment:**
 - **Node.js Version**: v18.12.0
 - **Redis Server Version**: 6.2.7
 - **Node Redis Version**: 4.5.1
 - **Platform**: macOS 13.0.1 (22A400)

**Comment by leibale** [comment] 2023-01-09 23:58
Duplicate of #2345
See [this comment](https://github.com/redis/node-redis/issues/2345#issuecomment-1365119737)

**Closed by leibale** 2023-01-09 23:58 UTC
Labels: Bug
