### ISSUE TITLE
Blows up on Node JS 12  

### ISSUE THREAD

**Issue by rick-rheo** [redis/node-redis#2136] opened 2022-05-16 23:59 UTC
**Environment:**
 - **Node Version****: 12.20.2
 - **Redis Server Version**:    Don't even get that far
 - **Node Redis Version**:   redis@4.1.0 
 - **Platform**: Pick one

Per your change log :
Dropped support for Node.js 10.x, the minimum supported Node.js version is now 12.x  <---

NO!   This happens.

```
$ node
Welcome to Node.js v12.20.2.
Type ".help" for more information.
> require('redis')
/Users/rheo/dev/projects/npm-redis-makes-me-sad/node_modules/redis/dist/index.js:42
            ...options?.modules
```

**Comment by leibale** [comment] 2022-05-17 10:10
Duplicate of #2117

**Closed by leibale** 2022-05-17 10:10 UTC
Labels: Bug
