### ISSUE TITLE
FT.SEARCH: Parameter MSORTBY throwing error

### ISSUE THREAD

**Issue by amansubhan** [redis/node-redis#1752] opened 2021-12-01 05:29 UTC
When I try to use MSORTBY argument for searching in full text index, it throws an error on call "Unknown argument `MSORTBY` at position 1 for <main>"

Query: 
```
await redisClient.ft.SEARCH('idx:res', query, {
        'MSORTBY': { BY: 'score', DIRECTION: "DESC" },
        'LIMIT': { from: 0, size: 2 },
    })
```

**Environment:**
 - **Node.js Version**: v16.13.0
 - **Redis Server Version**: 6.2.5
 - **Node Redis Version**: 4.0.0
 - **Platform**:Debian Bullseye

**Comment by leibale** [comment] 2021-12-01 06:23
Duplicate of #1749

**Closed by leibale** 2021-12-01 06:23 UTC
Labels: Bug
