### ISSUE TITLE
ZRANGE record retrieval 50% slower after upgrading to 4.0.4

### ISSUE THREAD

**Issue by v-flashpoint** [redis/node-redis#2002] opened 2022-02-22 16:54 UTC
Using similar code to the leaderboard for the bug I posted surrounding batch() and multi(), I'm afraid I've been seeing a ~50% decrease in performance after upgrading from 3.1.2 to 4.0.4.

I have a leaderboard of a million players, and I'm using ZREVRANGE to pull the player, plus two positions above and two positions below. The execution time has remained the same, but the retrieval time has gone from ~60ms per 10k to ~90ms per 10k. I initially thought it may be to do with promises, but the problem remains even in legacy mode.

Sample code
```

const redis = require('redis');
const client = redis.createClient({
	legacyMode: true
});
client.connect();

 client.on('connect', function() {
    console.log('Connected!');
    
    var initial = 1;
    var target = 10000;
    var multi = client.multi();
    multi.time();
    
    for(i = initial; i < target; i++){
	if(i < 2){
        	multi.ZRANGE('lb', 0, 5,'REV');
	}else{
		multi.ZRANGE('lb',(i -2), (i + 2),'REV');
	}
   }

   var start = performance.now();
    multi.exec(function(err, reply){
	//console.log(reply);
	var end = performance.now();

	redisstart = (parseInt(reply[0][0]) * 1000) + (parseInt(reply[0][1]) / 1000);
	redisend = (parseInt(reply[(reply.length - 1)][0]) * 1000) + (parseInt(reply[(reply.length - 1)][1]) / 1000);

	var execution_time = redisend - redisstart; // in milliseconds
        console.log('Execution time: '+execution_time);
	console.log('Retrieved in '+(end - start)+' ms');	
    });
});
```

**Environment:**
 - **Node.js Version**: 14.19.0
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.4
 - **Platform**: Ubuntu 20.04.3 LTS

**Comment by filipecosta90** [comment] 2022-04-06 11:43
given this issue was found to be related to redis itself ( and solved ) I believe we can close this node-redis one. 
core redis issue with all details: https://github.com/redis/redis/issues/10310

**Comment by v-flashpoint** [comment] 2022-04-06 12:53
I believe this regression was actually related to upgrading to node-redis 4.0.4, rather than changing the version of Redis, especially as the timings were showing no difference on the Redis end (listed as execution time in the code sample above) - instead, the extra delay seemed to be coming from node-redis. I'm just trying to confirm.

**Comment by filipecosta90** [comment] 2022-04-06 13:36
> I believe this regression was actually related to upgrading to node-redis 4.0.4, rather than changing the version of Redis, as I believe I ran both tests on Redis 6.2.6. The fact the timings were showing no difference on the Redis end (listed as execution time in the code sample above) also suggests this is a node-redis regression rather than something related to Redis itself. I'm just trying to confirm.

@v-flashpoint notice that even if the internal command latencies on redis stay nearly the same there is logic outside on the reply part that would be able to cause the regression and would not showup on the internal command latency value. 

WRT 
> I ran both tests on Redis 6.2.6

can you please confirm that on redis unstable ( or the latest 7.0-rc ) the issue is gone?

**Comment by v-flashpoint** [comment] 2022-04-06 14:23
More info, with updated code. It looks like the latency only seems to show up when running commands in a loop (possibly because it's been "warmed up" then?)

Updated code: 

```
client.on('connect', function() {
    console.log('Connected!');
    
    function getdata(n){
        loopinc = 10000;
        final = 1000000;

        if(n == 1){
            target = loopinc;
            initial = 1;
        }else{
            var initial = (n - 1) * loopinc;
            var target = n * loopinc;
        }
        console.log('start from: '+initial+', target '+target);

    var multi = client.multi();
    multi.time();
    
    for(i = initial; i < target; i++){
        if(i < 2){
            multi.zrange('lb', 0, 5, 'REV');
        }else{
            multi.zrange('lb',(i -2), (i + 2), 'REV');
        }
    }

   multi.time();
   var start = performance.now();
    multi.exec(function(err, reply){
	//console.log(reply);
	var end = performance.now();

	redisstart = (parseInt(reply[0][0]) * 1000) + (parseInt(reply[0][1]) / 1000);
	redisend = (parseInt(reply[(reply.length - 1)][0]) * 1000) + (parseInt(reply[(reply.length - 1)][1]) / 1000);

	var execution_time = redisend - redisstart; // in milliseconds
    console.log('Execution time: '+execution_time);
	console.log('Retrieved in '+(end - start)+' ms');	

    if(target < final){
        n++
        getdata(n);
    }
    });
    }
    getdata(1);
});
```

**Redis 6.2.6**

Node-redis 3.1.2: 

Execution time: 13~ms
Retrieved in: 70-75ms

Node-redis 4.0.4

Execution time: 13~ms
Retrieved in: 95-99ms

I haven't managed to install the unstable/7.0-rc version yet, as it's a bit more of an involved process than just doing it through apt-get, but the above results seem to suggest the difference being caused by the version of node-redis, rather than redis itself?

**Comment by v-flashpoint** [comment] 2022-04-06 14:37
Have just tested with the unstable build:

Node-redis 4.0.4
Execution time: 8ms
Retrieved in: 75-85ms.

So the execution time is quicker, and the retrieval time has dropped back down to roughly what it was before! LGTM.

**Closed** 2022-04-06 15:38 UTC
Labels: Bug
