### ISSUE TITLE
Optional chaining only supported with node > 14

### ISSUE THREAD

**Issue by ashercoren** [redis/node-redis#2119] opened 2022-05-04 04:29 UTC
In some commit from not long ago, an `optional chaining` was added to the code, in 2 places:
https://github.com/redis/node-redis/blob/master/index.ts#L52
https://github.com/redis/node-redis/blob/master/index.ts#L74

Optional chaining is only supported with node > 14, so this breaks code that is using node < 14.

**Environment:**
 - **Node.js Version**: 12
 - **Node Redis Version**: 4.1.0

**Comment by jmaguirrei** [comment] 2022-05-05 12:41
@ashercoren Hi, I am having similar issue, but I am using Node 16, an also tested Node 18, in a Docker container on Cloud Run environment.

Message is:
```
node:internal/process/promises:288
 triggerUncaughtException(err, true /* fromPromise */);
 ^

/usr/src/app/node_modules/@redis/client/dist/lib/cluster/cluster-slots.js:65
 if (node.client.options?.readonly)
 ^

SyntaxError: Invalid or unexpected token at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

Node.js v18.1.0
```

At file
https://github.com/redis/node-redis/blob/2ca1ba4f09c987b97215ac21e9d05b729331d985/packages/client/lib/cluster/cluster-slots.ts#L259

I dont remember changing anything, just started happen yesterday.

So, it seems the platform does not support optional chaining, even with Node 18.

I am also using esm@3.2.25, module loader. 

Any clue on this it's appreciatted.
Thanks :)

**Comment by mxia** [comment] 2022-05-06 20:42
Getting the same error [jmaguirrei](https://github.com/jmaguirrei) got after upgrading from 4.0.6 to 4.1.0.

**Comment by jmaguirrei** [comment] 2022-05-06 20:51
mxia, I solved the issue using esm-wallaby package instead of esm.
Hope it helps.

**Comment by njnygaard** [comment] 2022-05-06 22:21
Thank you for pointing that out @mxia. I would like to respect the `^` but I needed a fix now so I will be `@4.0.6`.

**Comment by leibale** [comment] 2022-05-09 12:47
[Node.js 12 is dead](https://nodejs.org/en/about/releases/)

**Comment by leibale** [comment] 2022-05-10 14:40
Duplicate of #2117

**Closed by leibale** 2022-05-10 14:40 UTC
Labels: Bug

**Comment by bcteam2020** [comment] 2022-08-13 07:36
> mxia, I solved the issue using esm-wallaby package instead of esm. Hope it helps.

Correct this is working if esm is replaced with esm-wallaby package

**Comment by PIYatGitHub** [comment] 2022-09-16 14:52
Our team had this issue with a serverless based application. It turned out to be that it used node 12 as runtime, as opposed to at least node 14. We changed the runtime property to `runtime: nodejs14.x` and we are back to smooth running mode again.
