### ISSUE TITLE
"redis.scan is not a function" in cluster mode

### ISSUE THREAD

**Issue by tiye** [redis/node-redis#2606] opened 2023-09-01 09:53 UTC
### Description

I was using `SCAN` since `KEYS` is not allowed in production mode. However as I move to cluster mode, running the same code base, I was told:

![image](https://github.com/redis/node-redis/assets/449224/5483cdcd-9ba4-477a-8cac-e720b71c76ce)

It looks like the code does not expose `SCAN` on purpose...
https://github.com/redis/node-redis/blob/294cbf8367295ac81cbe51ce2932493ab80493f1/packages/client/lib/cluster/commands.ts#L343

![image](https://github.com/redis/node-redis/assets/449224/c92ef9f9-4a42-4744-b501-eb38ffc1318e)

In my case I want to scan a list of keys I want to delete, what's the suggested way to do this in cluster mode with node-redis?

**Comment by sonht1109** [comment] 2023-09-12 08:36
Still no solutions for this?

**Comment by leibale** [comment] 2023-09-12 13:45
@tiye @sonht1109 you can loop over `cluster.masters` and use `scan/scanIterator` on each client:
```javascript
const results = await Promise.all(
    cluster.masters.map(async master => {
        const client = await cluster.nodeClient(master);
        // you can use client.scan or client.scanIterator here
    })
);
```
this should be added to the docs...

**Comment by leibale** [comment] 2023-09-12 13:46
Duplicate of #2446

**Closed by leibale** 2023-09-12 13:46 UTC
Labels: Documentation
