### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by cesco69** [redis/node-redis#2147] opened 2022-05-26 09:22 UTC
```
\node_modules\redis\dist\index.js:42
    ...options?.modules
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Environment:**
 - **Node.js Version**: 12.22.1
 - **Node Redis Version**: redis@4.1.0
 - **Platform**: Windows 7

**Comment by leibale** [comment] 2022-05-26 13:54
Duplicate of #2117

(Node 12 is "dead")

**Closed by leibale** 2022-05-26 13:54 UTC
Labels: Bug
