### ISSUE TITLE
Problem running tests locally

### ISSUE THREAD

**Issue by Niennienzz** [redis/node-redis#2588] opened 2023-07-26 17:22 UTC
### Description

Hello!

I'm having problems running tests locally.

I would like to test this library with [DragonflyDB](https://github.com/dragonflydb/dragonfly), which is an ultra-fast Redis-compatible memory store.

To start, I just want to see if tests work with Redis, but I am getting errors in the before-all/after-all hooks. It seems that the client was not able to connect to those Docker containers created by the test suite (if I remove the `testUtils.testWithClient` chunk, the test works). Is there any documentation on this that I missed?

Thank you so much for the help in advance!

### Node.js Version

Node.js v20.3.1

### Redis Server Version

6.2.10 (locally, pulled by the test suite)

### Node Redis Version

4.6.7

### Platform

MacOS X

### Logs

```bash
cd packages/client && nyc -r text-summary -r lcov mocha -r source-map-support/register -r ts-node/register './lib/commands/HGET.spec.ts'


  HGET
    1) "before all" hook for "transformArguments"

  2) "after all" hook in "{root}"

  0 passing (32s)
  2 failing

  1) HGET
       "before all" hook for "transformArguments":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/zhehuizhou/workspace/dragonfly/node-redis/packages/client/lib/commands/HGET.spec.ts)
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7)

  2) "after all" hook in "{root}":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7)
```

**Comment by leibale** [comment] 2023-07-31 19:10
Due to the differences in how docker works on different operating systems, the tests only work on Linux at the moment :(

Duplicate of #2358

**Closed by leibale** 2023-07-31 19:10 UTC
Labels: Bug
