### ISSUE TITLE
Uncaught Exception: TypeError: Cannot destructure property 'resolve' of '__classPrivateFieldGet(...).shift(...)' as it is undefined

### ISSUE THREAD

**Issue by Alastair-Spencer** [redis/node-redis#2626] opened 2023-10-11 07:15 UTC
### Description

Hello 👋🏻 

Starting to add some resillency to our codebase and I was testing what would happen when the max clients have been reached. 

I have ran `config set maxclients 1` in my Redis server and started the project to see how this would be handled.

**This fails with the following:**
  - ConnectionTimeoutError
  - TypeError
  - SocketClosedUnexpectedlyError
  
> Replication code  
  
```ts
      client = createClient({
        url: 'redis://localhost:6379',
        socket: {
          connectTimeout: 1000,
        },
        pingInterval: 4 * 60 * 1000,
      });

      client.on('error', (err) => {
        console.log('Redis Error', err);
      });
      client.on('connect', () => console.log('Redis client is connecting'));
      client.on('reconnecting', () => console.log('Redis is reconnecting'));
      client.on('ready', () => console.log('Redis client is ready'));
```
  
### Node.js Version

18.17.1

### Redis Server Version

7.2.1

### Node Redis Version

4.6.10

### Platform

MacOS (Docker redis-stack)

### Logs

```bash
ConnectionTimeoutError: Connection timeout
    at Socket.<anonymous> (/Users/alastair/projects/repo/node_modules/@redis/client/dist/lib/client/socket.js:177:124)
    at Object.onceWrapper (node:events:628:28)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at Socket._onTimeout (node:net:571:8)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)

log: Redis is reconnecting
log: Redis client is connecting
log: Redis client is ready

Uncaught Exception: TypeError: Cannot destructure property 'resolve' of '__classPrivateFieldGet(...).shift(...)' as it is undefined.
    at Object.onReply (/Users/alastair/projects/repo/node_modules/@redis/client/dist/lib/client/commands-queue.js:62:25)
    at RESP2Decoder.write (/Users/alastair/projects/repo/node_modules/@redis/client/dist/lib/client/RESP2/decoder.js:119:26)
    at RedisCommandsQueue.onReplyChunk (/Users/alastair/projects/repo/node_modules/@redis/client/dist/lib/client/commands-queue.js:154:72)
    at RedisSocket.<anonymous> (/Users/alastair/projects/repo/node_modules/@redis/client/dist/lib/client/index.js:394:84)
    at RedisSocket.emit (node:events:514:28)
    at RedisSocket.emit (node:domain:489:12)
    at Socket.<anonymous> (/Users/alastair/projects/repo/node_modules/@redis/client/dist/lib/client/socket.js:201:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at Socket.<anonymous> (/Users/alastair/projects/repo/node_modules/@redis/client/dist/lib/client/socket.js:194:118)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:323:12)
```

**Comment by leibale** [comment] 2023-10-11 17:02
Probably a duplicate of #2417

**Closed** 2023-10-17 15:21 UTC
Labels: Bug

**Comment by Alastair-Spencer** [comment] 2024-01-11 08:08
@leibale 👋🏻 Hope you're well and had a good Christmas / New Year! 

It seems that https://github.com/redis/node-redis/issues/2632 has fixed the problem. It's not been noted in this change as a direct fix but it's been fixed by proxy.

**Comment by p-janik** [comment] 2024-04-03 08:57
Hey, it looks like we just hit into this problem recently:
```
TypeError: Cannot destructure property 'resolve' of '__classPrivateFieldGet(...).shift(...)' as it is undefined.
    at Object.onReply (/opt/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:62:25)
    at RESP2Decoder.write (/opt/app/node_modules/@redis/client/dist/lib/client/RESP2/decoder.js:119:26)
    at RedisCommandsQueue.onReplyChunk (/opt/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:154:72)
    at RedisSocket.<anonymous> (/opt/app/node_modules/@redis/client/dist/lib/client/index.js:410:84)
    at RedisSocket.emit (node:events:517:28)
    at RedisSocket.emit (node:domain:489:12)
    at Socket.<anonymous> (/opt/app/node_modules/@redis/client/dist/lib/client/socket.js:201:42)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:128:17)
```

We are already on the latest version of redis `4.6.13`

**Comment by mattfiocca** [comment] 2024-08-15 16:20
Same here, node-redis 4.7.0, node 18.14.0.

But in our case we have a client-facing gRPC service, that when a stream is initiated we perform a pSubscribe for that stream call. If the gRPC client<->server socket crashes for whatever reason (like a proto serialization error), and we don't call `pUnsubscribe` or `disconnect()` with redis, we get this error almost exactly 60 seconds after the gRPC client went away. I'm still trying to figure out where exactly this is being thrown in our own code, so I can tell if it's an issue on our end or not. 

I'm thinking it might have something to do with garbage collection, since the redis connection and client object live inside the gRPC call initiator / scope. When node kills the gRPC client the redis object goes with it, without us having a chance to call unsubscribe or disconnect.

```
TypeError: Cannot destructure property 'resolve' of '__classPrivateFieldGet(...).shift(...)' as it is undefined.
    at Object.onReply (/usr/src/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:62:25)
    at RESP2Decoder.write (/usr/src/app/node_modules/@redis/client/dist/lib/client/RESP2/decoder.js:119:26)
    at RedisCommandsQueue.onReplyChunk (/usr/src/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:154:72)
    at RedisSocket.<anonymous> (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:420:84)
    at RedisSocket.emit (node:events:513:28)
    at RedisSocket.emit (node:domain:489:12)
    at Socket.<anonymous> (/usr/src/app/node_modules/@redis/client/dist/lib/client/socket.js:201:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
```

**Comment by DoobleD** [comment] 2024-11-10 17:51
Hi, same here, even with https://github.com/redis/node-redis/pull/2653. For us it happens after failovers when we use CLIENT KILL to force clients to reconnect to the new master.

```
TypeError: Cannot destructure property 'resolve' of '__classPrivateFieldGet(...).shift(...)' as it is undefined.
    at Object.onReply (/opt/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:62:25)
    at RESP2Decoder.write (/opt/app/node_modules/@redis/client/dist/lib/client/RESP2/decoder.js:119:26)
    at RedisCommandsQueue.onReplyChunk (/opt/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:154:72)
    at RedisSocket.<anonymous> (/opt/app/node_modules/@redis/client/dist/lib/client/index.js:411:84)
    at RedisSocket.emit (node:events:519:28)
    at Socket.<anonymous> (/opt/app/node_modules/@redis/client/dist/lib/client/socket.js:202:42)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
```
