### ISSUE TITLE
commandOptions not allowing `returnBuffers` option

### ISSUE THREAD

**Issue by matt-wormley** [redis/node-redis#1814] opened 2022-01-04 16:23 UTC
When trying to use the documented `returnBuffers`commandOption, I'm receiving the following error

```
(property) returnBuffers: boolean
Argument of type '{ returnBuffers: boolean; }' is not assignable to parameter of type 'ClientCommandOptions'.
  Object literal may only specify known properties, and 'returnBuffers' does not exist in type 'ClientCommandOptions'.ts(2345)
```

here's my example code

```
await _client.hGetAll(commandOptions({ returnBuffers: true }), key);
```

**Environment:**
 - **Node.js Version**: 16
 - **Redis Server Version**: n/a
 - **Node Redis Version**: 4.0.1
 - **Platform**: MacOS 11.16.1

**Comment by leibale** [comment] 2022-01-04 23:33
Duplicate of #1800

the `returnBuffers` options wasn't release to npm yet

**Closed** 2022-01-04 23:33 UTC
Labels: Bug

**Comment by matt-wormley** [comment] 2022-01-05 00:32
o i c. The current version in github sources is 4.0.1 but it just hasn't been bumped since the last npm release. Thanks and sorry for the dup.
