### ISSUE TITLE
RESP3 protocol fails 

### ISSUE THREAD

**Issue by vortex314** [redis/node-redis#2089] opened 2022-04-19 21:30 UTC
In RESP3 redis interface the same redis client can subscribe and publish without additional connection. 
However switching to RESP3 is not possible. 
```
var redisClient = redis.createClient(REDIS_SERVER);

redisClient.on('error', (err) => console.log('Redis Client Error', err))
redisClient.on('connect', () => console.log('Redis Client connecting'))
redisClient.on('ready', () => {
    console.log('Redis Client ready')
       redisClient.hello({protover:"3"})
    //   redisClient.sendCommand(["hello", "3"])

    console.log(" psubscribe and hello ")
})
redisClient.on('reconnecting', () => console.log('Redis Client reconnecting'))
redisClient.connect()
```
fails with 
```
nodemon] starting `node server.js index.js`
WebSocket server started at ws://locahost:3030
Redis Client connecting
Redis Client ready
 psubscribe and hello 
/home/lieven/workspace/redisDashboard/server/node_modules/redis-parser/lib/parser.js:190
  const err = new ParserError(
              ^

ParserError: Protocol error, got "%" as reply type byte
    at handleError (/home/lieven/workspace/redisDashboard/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/home/lieven/workspace/redisDashboard/server/node_modules/redis-parser/lib/parser.js:304:14) {
  offset: 1,
  buffer: '{"type":"Buffer","data":[37,55,13,10,36,54,13,10,115,101,114,118,101,114,13,10,36,53,13,10,114,101,100,105,115,13,10,36,55,13,10,118,101,114,115,105,111,110,13,10,36,53,13,10,54,46,48,46,57,13,10,36,53,13,10,112,114,111,116,111,13,10,58,51,13,10,36,50,13,10,105,100,13,10,58,49,56,54,13,10,36,52,13,10,109,111,100,101,13,10,36,49,48,13,10,115,116,97,110,100,97,108,111,110,101,13,10,36,52,13,10,114,111,108,101,13,10,36,54,13,10,109,97,115,116,101,114,13,10,36,55,13,10,109,111,100,117,108,101,115,13,10,42,49,13,10,37,50,13,10,36,52,13,10,110,97,109,101,13,10,36,49,48,13,10,116,105,109,101,115,101,114,105,101,115,13,10,36,51,13,10,118,101,114,13,10,58,49,48,52,49,48,13,10,62,51,13,10,36,49,48,13,10,112,115,117,98,115,99,114,105,98,101,13,10,36,49,55,13,10,97,112,112,58,110,111,116,105,102,105,99,97,116,105,111,110,115,13,10,58,49,13,10]}'                                                                                                  
}
```
The same effect pops up if you use an older version redis-cli connecting to a RESP3 ready redis-server.

**Comment by leibale** [comment] 2022-04-19 22:40
Duplicate of #1502

RESP 3 is not yet supported :(
We plan to add support for it in 4.2.0

**Closed by leibale** 2022-04-19 22:40 UTC

**Comment by gabzim** [comment] 2022-07-26 18:37
4.2.0 is out, does it mean there's support for RESP3 now? I tried looking at the changelog but it seems like it's missing versions since Jan this year.

**Comment by leibale** [comment] 2022-07-26 18:51
@gabzim unfortunately, RESP3 is not yet supported 
You can see the release notes in https://github.com/redis/node-redis/releases

**Comment by varadero** [comment] 2023-12-29 22:24
Hopefully we will have RESP3 support in v5. I can see a pull request - https://github.com/redis/node-redis/pull/2485

**Comment by leibale** [comment] 2024-01-16 20:01
@varadero RESP3 and sentinel support are the main features of v5 :)
