### ISSUE TITLE
>= 4.1.0 no longer works with node 12

### ISSUE THREAD

**Issue by HughePaul** [redis/node-redis#2146] opened 2022-05-25 16:32 UTC
node-redis >= 4.1.0 no longer works with node 12.

Probably worth putting in the readme or migration docs, or possibly it should have been a semver major release.

**Comment by leibale** [comment] 2022-05-26 13:54
Duplicate of #2117 

You are 100% right, it should have been a major release.

**Closed by leibale** 2022-05-26 13:54 UTC
Labels: Bug
