### ISSUE TITLE
dynamic prefix

### ISSUE THREAD

**Issue by wangsenyan** [redis/node-redis#1872] opened 2022-01-24 08:00 UTC
hi, can i set prefix dynamic? 
for example i exec commond get:  
```js
 get('id',{prefix:"aaa"},callback);
 get('id',{prefix:"bbb"},callback);
```
set prefix by option dynamic,  
so i don't need to init multi client  

thanks

**Comment by leibale** [comment] 2022-01-24 18:16
Duplicate of #1657?

**Closed** 2023-01-24 23:20 UTC
Labels: Pending Author Input, Question
